[project]
name = "ai-transcript-summarizer"
version = "0.1.0"
description = "The main idea of the project is to create a web application which provides podcast summaries. These summaries will be generated via an offline data engineering process powered by an open-source LLM."
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = []
